-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 21:58:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL,
  `nombreTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDeparCarrera` INT NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDeparCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` MEDIUMTEXT NOT NULL,
  `tipoUsuario` INT NOT NULL,
  `deparCarrera` INT NOT NULL,
  `login` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `usuarioTipo_idx` (`tipoUsuario` ASC) VISIBLE,
  INDEX `usuarioDepar_idx` (`deparCarrera` ASC) VISIBLE,
  INDEX `fk_Usuario_Login1_idx` (`login` ASC) VISIBLE,
  CONSTRAINT `usuarioTipo`
    FOREIGN KEY (`tipoUsuario`)
    REFERENCES `mydb`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioDepar`
    FOREIGN KEY (`deparCarrera`)
    REFERENCES `mydb`.`Departamento` (`idDeparCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Login1`
    FOREIGN KEY (`login`)
    REFERENCES `mydb`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aula` (
  `idAula` INT NOT NULL,
  `nombreAula` VARCHAR(45) NOT NULL,
  `departamento` INT NOT NULL,
  `taller` INT NOT NULL,
  PRIMARY KEY (`idAula`),
  INDEX `aulaDepar_idx` (`departamento` ASC) VISIBLE,
  CONSTRAINT `aulaDepar`
    FOREIGN KEY (`departamento`)
    REFERENCES `mydb`.`Departamento` (`idDeparCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `idCarrera` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idCarrera`),
  INDEX `fk_Carrera_DeparCarrera1_idx` (`departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Carrera_DeparCarrera1`
    FOREIGN KEY (`departamento`)
    REFERENCES `mydb`.`Departamento` (`idDeparCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Microtaller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Microtaller` (
  `idMicrotaller` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`idMicrotaller`),
  INDEX `fk_Microtaller_Usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Microtaller_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tutoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tutoria` (
  `idTutoria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `fechaInicio` VARCHAR(45) NOT NULL,
  `fechaFin` VARCHAR(45) NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`idTutoria`),
  INDEX `fk_Tutoria_Usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Tutoria_Usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
