-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 15:24:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestorPedidos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GestorPedidos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestorPedidos` DEFAULT CHARACTER SET utf8 ;
USE `GestorPedidos` ;

-- -----------------------------------------------------
-- Table `GestorPedidos`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Login` (
  `idLogin` INT NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`TipoPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`TipoPersona` (
  `idTipoPersona` INT NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nombreDepartamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Carrera` (
  `idCarrera` INT NOT NULL,
  `nombreCarrera` VARCHAR(45) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`idCarrera`),
  INDEX `fk_Carrera_Departamento1_idx` (`departamento` ASC) VISIBLE,
  CONSTRAINT `fk_Carrera_Departamento1`
    FOREIGN KEY (`departamento`)
    REFERENCES `GestorPedidos`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `emailPersona` VARCHAR(45) NULL,
  `tipoPersona` INT NOT NULL,
  `carrera` INT NOT NULL,
  `login` INT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Login_idx` (`login` ASC) VISIBLE,
  INDEX `fk_Persona_TipoPersona1_idx` (`tipoPersona` ASC) VISIBLE,
  INDEX `fk_Persona_Carrera1_idx` (`carrera` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Login`
    FOREIGN KEY (`login`)
    REFERENCES `GestorPedidos`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_TipoPersona1`
    FOREIGN KEY (`tipoPersona`)
    REFERENCES `GestorPedidos`.`TipoPersona` (`idTipoPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Carrera1`
    FOREIGN KEY (`carrera`)
    REFERENCES `GestorPedidos`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`Tutoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Tutoria` (
  `idTutoria` INT NOT NULL,
  `motivo` VARCHAR(45) NULL,
  `fecha` DATE NOT NULL,
  `personaTutoria` INT NOT NULL,
  PRIMARY KEY (`idTutoria`),
  INDEX `fk_Tutoria_Persona1_idx` (`personaTutoria` ASC) VISIBLE,
  CONSTRAINT `fk_Tutoria_Persona1`
    FOREIGN KEY (`personaTutoria`)
    REFERENCES `GestorPedidos`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`Microtaller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Microtaller` (
  `idMicrotaller` INT NOT NULL,
  `nombreMicrotaller` VARCHAR(45) NOT NULL,
  `motivoMicrotaller` VARCHAR(45) NULL,
  PRIMARY KEY (`idMicrotaller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`Aula` (
  `idAula` INT NOT NULL,
  `nombreAula` VARCHAR(45) NOT NULL,
  `urlAula` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`PersonaAula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`PersonaAula` (
  `Persona_idPersona` INT NOT NULL,
  `Aula_idAula` INT NOT NULL,
  PRIMARY KEY (`Persona_idPersona`, `Aula_idAula`),
  INDEX `fk_Persona_has_Aula_Aula1_idx` (`Aula_idAula` ASC) VISIBLE,
  INDEX `fk_Persona_has_Aula_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_has_Aula_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `GestorPedidos`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Aula_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `GestorPedidos`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestorPedidos`.`MicrotallerPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestorPedidos`.`MicrotallerPersona` (
  `Microtaller_idMicrotaller` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`Microtaller_idMicrotaller`, `Persona_idPersona`),
  INDEX `fk_Microtaller_has_Persona_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  INDEX `fk_Microtaller_has_Persona_Microtaller1_idx` (`Microtaller_idMicrotaller` ASC) VISIBLE,
  CONSTRAINT `fk_Microtaller_has_Persona_Microtaller1`
    FOREIGN KEY (`Microtaller_idMicrotaller`)
    REFERENCES `GestorPedidos`.`Microtaller` (`idMicrotaller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Microtaller_has_Persona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `GestorPedidos`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
