-- MySQL Script generated by MySQL Workbench
-- 09/26/18 18:11:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pedidos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pedidos` ;

-- -----------------------------------------------------
-- Schema pedidos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedidos` DEFAULT CHARACTER SET utf8 ;
USE `pedidos` ;

-- -----------------------------------------------------
-- Table `pedidos`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `pedidos`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos`.`Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos`.`Aula` ;

CREATE TABLE IF NOT EXISTS `pedidos`.`Aula` (
  `idAula` INT NOT NULL AUTO_INCREMENT,
  `dependencia` VARCHAR(45) NOT NULL,
  `nombreDelAula` VARCHAR(45) NOT NULL,
  `nombreDelProfesor` VARCHAR(45) NOT NULL,
  `emailDelProfesor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
